[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "directory-tree>=1.0.0",
    "fastapi>=0.115.12",
    "openai>=1.76.0",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
